app/routes/books.py
from flask import Blueprint, current_app, render_template

from app.dao.books import BookDAO
from app.dao.pagination import (
    get_limit,
    get_page_num,
    get_pagination_num,
    get_start_index,
)

book_routes = Blueprint("books", __name__, url_prefix="/books")


@book_routes.get("/")
def get_index():
    dao = BookDAO(current_app.driver)

    page_num = get_page_num()
    limit = get_limit()
    start_index = get_start_index(page_num, limit)
    total_num = dao.get_total_count()
    pagination_num = get_pagination_num(total_num, limit)

    books = dao.all(start_index, limit)

    return render_template(
        "books.html",
        books=books,
        current_page=page_num,
        total_num=total_num,
        pagination_num=pagination_num,
        limit=limit,
    )


@book_routes.get("/<id>/")
def get_detail(id):
    dao = BookDAO(current_app.driver)
    book = dao.detail(id)
    related_books = dao.relate(id)

    if book:
        return render_template(
            "book-detail.html",
            book=book,
            related_books=related_books,
        )
    return render_template("book-not-found.html")

app/routes/graphs.py
from flask import Blueprint, render_template

graph_routes = Blueprint("graphs", __name__, url_prefix="/graphs")


@graph_routes.get("/")
def get_graphs():
    return render_template("graphs.html")

app/templates/base.html
<!doctype html>
<html lang="ja" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">


    <title>{% block title %}LibroNet{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/neovis.js@2.0.2"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/graph.js') }}"></script>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>

<body onload="draw()" class="d-flex flex-column h-100">
    <!-- <body onload="draw()"> -->
    <header class="p-3 mb-3 border-bottom">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                    <!-- <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                        <use xlink:href="#bootstrap"></use>
                    </svg> -->
                    <img src="/images/logo.svg" alt="LibraNet logo" width="60" height="50">
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle link-dark" href="#" id="navbarDarkDropdownMenuLink"
                            role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Books
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li><a class="dropdown-item" href="{{ url_for('books.get_index') }}">All</a></li>
                            {% for genre in genres %}
                            <li><a class="dropdown-item" href="/genres/{{genre.name_en}}/">{{genre.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a href="{{ url_for('graphs.get_graphs') }}" class="nav-link px-2 link-secondary">Graph</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="/search">
                    <input type="search" class="form-control" placeholder="Search..." aria-label="Search" name="q">
                </form>
            </div>
        </div>
    </header>

    <!-- Begin page content -->
    <main class="flex-shrink-0 mb-5">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <span class="text-muted">LibroNet</span>
        </div>
    </footer>

</body>

</html>

app/templates/book-detail.html
{% extends 'base.html' %}

{% block title %}{{ book[0]['title'] }} {{ book[0]['sub_title'] }} | Books | {{ super() }}{% endblock %}

{% block content %}
<section class="pt-5 pb-0">
    <div class="container">
        <div class="row g-0 g-lg-5">

            <!-- Left sidebar START -->
            <div class="col-lg-4">
                <div class="row">
                    <div class="col-md-6 col-lg-12">
                        <div class="card shadow p-2 mb-4 text-center">
                            <div class="rounded-3">
                                <!-- Image -->
                                {% if book['b']['image'] %}
                                <img src="/images/books/{{ book['b']['image'] }}" class="card-img"
                                    alt="{{ book['b']['title'] }} {{ book['b']['sub_title'] }}">
                                {% else %}
                                <img src="/images/books/no-image.jpg" class="card-img" alt="no-iamge">
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 col-lg-12">
                        <div class="card card-body shadow p-4 mb-4">

                            <div class="d-flex align-items-center mb-4">
                                <span class="icon-md mb-0 bg-light rounded-3"><i
                                        class="fas fa-graduation-cap"></i></span>
                                <div class="ms-3">
                                    <h6 class="mb-2">出版者</h6>
                                    <p class="mb-1 small">{{ book.publisher }}</p>
                                </div>
                            </div>

                            <div class="d-flex align-items-center mb-4">
                                <span class="icon-md mb-0 bg-light rounded-3"><i
                                        class="fas fa-graduation-cap"></i></span>
                                <div class="ms-3">
                                    <h6 class="mb-2">著者</h6>
                                    {% for author in book.authors %}
                                    <p class="mb-1 small">{{ author }}</p>
                                    {% endfor %}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- Left sidebar END -->

            <!-- Main content START -->
            <div class="col-lg-8">

                <!-- Title -->
                <h3 class="mb-0">{{ book['b']['title'] }}</h3>
                <h5 class="mb-0">{{ book['b']['sub_title'] }}</h5>
                <!-- Content -->
                <p class="mt-4">
                    {{ book['b']['summary'] | safe }}
                </p>
                <!-- Personal info -->
                <ul class="list-group list-group-borderless">
                    <li class="list-group-item px-0">
                        <span class="h6 fw-light"><i
                                class="fas fa-fw fa-map-marker-alt text-primary me-1 me-sm-3"></i>発売:</span>
                        <span>{{ book['b']['publication_year'] }}年</span>
                    </li>
                    <li class="list-group-item px-0">
                        <span class="h6 fw-light"><i
                                class="fas fa-fw fa-envelope text-primary me-1 me-sm-3"></i>URL:</span>
                        <a href="{{ book['b']['url'] }}" target="_blank"><span>{{ book['b']['url'] }}</span></a>
                    </li>
                </ul>
            </div>
            <!-- Main content END -->

        </div>
    </div>
</section>
{% if related_books %}
<h5 class="mt-5">関連のある本</h5>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for book in related_books %}
    <div class="col">
        <div class="card shadow-sm">
            <div class="text-center">
                {% if book['related_book']['image'] %}
                <img src="/images/books/{{ book['related_book']['image'] }}" height="250px"
                    alt="{{ book['related_book']['title'] }}">
                {% else %}
                <img src="/images/books/no-image.jpg" height="250px" alt="no-iamge">
                {% endif %}
            </div>
            <div class="card-body">
                <p class="card-text">{{ book['related_book']['title'] }} {{ book['related_book']['sub_title'] }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="/books/{{ book['related_book']['book_id'] }}/"><button type="button"
                                class="btn btn-sm btn-outline-secondary">View</button></a>
                        <!-- <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button> -->
                    </div>
                    <div>
                        {% for author in book['authors'] %}
                        <small class="text-muted" style="display: block;">{{ author.name }}</small>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

app/templates/book-not-found.html
{% extends 'base.html' %}

{% block title %}not found | Books | {{ super() }}{% endblock %}

{% block content %}
お探しの本が見つかりませんでした。
{% endblock %}

app/templates/books.html
{% extends 'base.html' %}

{% block title %} {% if title %}{{ title.name }} {% else %} Books {% endif %} | {{ super() }}{% endblock %}

{% block content %}

<h5 class="mt-5 mb-4">
    {% if title %}{{ title.name }}{% endif %}
</h5>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mb-2">
    {% for book in books %}
    <div class="col">
        <div class="card shadow-sm">
            <div class="text-center">
                {% if book['b']['image'] %}
                <img src="/images/books/{{book['b']['image']}}" height="250px" alt="{{book['b']['title']}}">
                {% else %}
                <img src="/images/books/no-image.jpg" height="250px" alt="no-iamge">
                {% endif %}
            </div>
            <div class="card-body">
                <p class="card-text">{{book['b']['title']}} {{book['b']['sub_title']}}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="/books/{{book['b']['book_id']}}/"><button type="button"
                                class="btn btn-sm btn-outline-secondary">View</button></a>
                    </div>
                    <div>
                        {% for r in book['authors'] %}
                        <small class="text-muted" style="display: block;">{{r.name}}</small>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% if total_num > limit %}
<section class="mt-5 al">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {% if current_page == 1 %} disabled {% endif %}">
                <a class="page-link" href="?page=1&limit={{limit}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for i in range(pagination_num) %}
            <li class="page-item {% if current_page == i + 1 %} active {% endif %}">
                <a class="page-link" href="?page={{i+1}}&limit={{limit}}">{{i+1}}</a>
            </li>
            {% endfor %}
            <li class="page-item {% if current_page == pagination_num %} disabled {% endif %}">
                <a class="page-link" href="?page={{pagination_num}}&limit={{limit}}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</section>
{% endif %}
{% endblock %}

app/templates/graphs.html
{% extends 'base.html' %}

{% block title %}Graph | {{ super() }}{% endblock %}

{% block content %}
<!-- <div onload="draw()"> -->
<div id="viz"></div>
<!-- </div> -->
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="p-4 p-md-5 mb-4 text-white rounded bg-image">

    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">LibroNet</h1>
        <p class="lead my-3">Visualize your reading history and visualize your relationship with books.</p>
    </div>
</div>
<h5 class="mt-5">最近読んだ本</h5>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in objects %}
    <div class="col">
        <div class="card shadow-sm">
            <div class="text-center">
                {% if object['b']['image'] %}
                <img src="/images/books/{{object['b']['image']}}" height="250px" alt="{{object['b']['title']}}">
                {% else %}
                <img src="/images/books/no-image.jpg" height="250px" alt="no-iamge">
                {% endif %}
            </div>

            <div class="card-body">
                <p class="card-text">{{object['b']['title']}} {{object['b']['sub_title']}}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="/books/{{object['b']['book_id']}}/"><button type="button"
                                class="btn btn-sm btn-outline-secondary">View</button></a>
                        <!-- <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button> -->
                    </div>
                    <div>
                        {% for r in object['authors'] %}
                        <small class="text-muted" style="display: block;">{{r.name}}</small>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/search.html
{% extends 'base.html' %}

{% block title %}Search | {{ super() }}{% endblock %}

{% block content %}

<h5 class="mt-5 mb-4">
    検索結果： {{ search_word }} ( {{ total_num }} 件)
</h5>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mb-2">
    {% for book in books %}
    <div class="col">
        <div class="card shadow-sm">
            <div class="text-center">
                <img src="/images/books/{{book['b']['image']}}" height="250px" alt="{{book['b']['title']}}">
            </div>
            <div class="card-body">
                <p class="card-text">{{book['b']['title']}} {{book['b']['sub_title']}}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="/books/{{book['b']['book_id']}}/"><button type="button"
                                class="btn btn-sm btn-outline-secondary">View</button></a>
                        <!-- <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button> -->
                    </div>
                    <div>
                        {% for r in book['authors'] %}
                        <small class="text-muted" style="display: block;">{{r.name}}</small>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% if total_num > limit %}
<section class="mt-5 al">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {% if current_page == 1 %} disabled {% endif %}">
                <a class="page-link" href="?q={{search_word}}&page=1&limit={{limit}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for i in range(pagination_num) %}
            <li class="page-item {% if current_page == i + 1 %} active {% endif %}">
                <a class="page-link" href="?q={{search_word}}&page={{i+1}}&limit={{limit}}">{{i+1}}</a>
            </li>
            {% endfor %}
            <li class="page-item {% if current_page == pagination_num %} disabled {% endif %}">
                <a class="page-link" href="?q={{search_word}}&page={{pagination_num}}&limit={{limit}}"
                    aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</section>
{% endif %}
{% endblock %}